include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # مشروعنا يعتمد snake_case عمدًا داخل الموديلات والـ APIs
    non_constant_identifier_names: ignore
    constant_identifier_names: ignore

linter:
  rules:
    # لأننا نعتمد snake_case في المتغيرات والدوال أيضًا
    non_constant_identifier_names: false
    constant_identifier_names: false

    # لتجنب رسائل "Unnecessary use of multiple underscores"
    unnecessary_underscores: false
